samvera/hydra-works

Gemfile
lib/hydra/works.rb
lib/hydra/works/models/concerns/collection_behavior.rb
lib/hydra/works/models/concerns/generic_file_behavior.rb
lib/hydra/works/models/concerns/generic_work_behavior.rb
lib/hydra/works/vocab/works_terms.rb
spec/hydra/works/models/generic_work_spec.rb

NOTE: The Gemfile ties active_fedora and active-triples to specific branches that allows for multiple types.

add multiple types for collections, generic works, and generic files

---

Gemfile

Hydra::Works should use a released version of hydra-pcdm. @flyingzumwalt after this is merged, I can cut a release of hydra-works.

Use hydra-pcdm 0.0.1

---

Gemfile
lib/hydra/works/models/concerns/generic_file/contained_files.rb
lib/hydra/works/services/generic_file/add_file.rb
spec/hydra/works/models/concerns/generic_file/contained_files_spec.rb
spec/hydra/works/services/generic_file/add_file_spec.rb

the service relies on the :versioning karg instead of calling .versionable? on the File object.  This removes  the need for a VersionedFile class.

AddFile service relies on kargs to know whether to version 

---

lib/hydra/works/services/generic_file/add_file.rb
spec/hydra/works/services/generic_file/add_file_spec.rb

I'm open to changing how the service responds to this situation, but it needs to do something.  Without the change, it ignores validation completely, meaning that it sometimes attempts to create file versions on unsaved objects and sometimes adds files to fedora even though the parent is not valid (meaning that, for example, a file with a virus would be saved to fedora even if the parent detected the virus)

AddFileToGenericFile validates the generic_file before attempting to save

---

spec/hydra/works/models/concerns/generic_file/contained_files_spec.rb
spec/hydra/works/models/concerns/generic_file/versioned_content_spec.rb
spec/hydra/works/services/collection/remove_collection_spec.rb
spec/hydra/works/services/collection/remove_generic_work_spec.rb
spec/hydra/works/services/collection/remove_related_object_spec.rb
spec/hydra/works/services/generic_file/add_file_to_generic_file_spec.rb
spec/hydra/works/services/generic_file/add_generic_file_spec.rb
spec/hydra/works/services/generic_file/add_related_object_spec.rb
spec/hydra/works/services/generic_file/remove_generic_file_spec.rb
spec/hydra/works/services/generic_file/remove_related_object_spec.rb
spec/hydra/works/services/generic_file/upload_file_spec.rb
spec/hydra/works/services/generic_work/remove_generic_file_spec.rb
spec/hydra/works/services/generic_work/remove_generic_work_spec.rb
spec/hydra/works/services/generic_work/remove_related_object_spec.rb

Fixes #148 
* Removing unnecessary saves and reloads
* Combining a few tests that need to save objects to avoid repeated object creation
* On my machine, reduces test duration from 268 to 45 sec (~6x faster)

Improving test performance

---

hydra-works.gemspec

Also, update gitignore for config dir and vim swp files.  We use a different config/fedora.yml than the default and others might do so as well.  It's not required for hydra-works so config/ can be ignored for the time being.

Update activefedora-aggregation version to ~> 0.3

---

lib/hydra/works/services/generic_file/add_file_to_generic_file.rb
lib/hydra/works/services/generic_file/persist_derivative.rb
lib/hydra/works/services/generic_file/upload_file.rb
spec/hydra/works/models/concerns/generic_file/versioned_content_spec.rb
spec/hydra/works/services/generic_file/add_file_to_generic_file_spec.rb
spec/hydra/works/services/generic_file/persist_derivative_spec.rb
spec/hydra/works/services/generic_file/upload_file_spec.rb

Refactor file check to responds_to? :read.
If present use :mime_type and :original_name of file.
Add metadata defaults depending on available methods.
Add test for technical metadata defaults for AddFileToGenericFile.
Change PersistDerivative to use IO in lieu of path.
Remove desination_name from call signature in PersistDerivative.
Refactor UploadFile to use IO in lieu of path.
Remove argument checks from UploadFile. They are done in
AddFileToGenericFile.
Remove mime_type and original_name from args of UploadFile.
Update specs to pass File object instead of path.
Mock methods :mime_type and :original_name for testing Files.

Update AddFileToGenericFile use IO in lieu of path.

---

lib/hydra/works.rb
spec/hydra/works_spec.rb

deprecate validations in works.rb and use works_generic_file? works_generic_work? and works_collection? instead.
This is to address this issue:  https://github.com/projecthydra-labs/hydra-works/issues/164
If this looks good, I can fix spec/hydra/works_spec.rb to use the new methods and not the deprecated methods.  Should I do that as part of this issue?
-Jose

deprecate methods in works.rb for issue 164

---

lib/hydra/works/vocab/works_terms.rb

We really shouldn't use "hydra.org", since that's something completely different.

Changing RDF Vocabulary namespace to projecthydra.org

---

lib/hydra/works/models/characterization/document_schema.rb
lib/hydra/works/models/concerns/file_set/characterization/document.rb
spec/hydra/works/services/characterization_service_spec.rb

Fixes #226
Remove custom mapping of file_title and file_author.
This will avoid over writing existing title and author values.

Remove mapping of file_title and file_author

---

.rubocop.yml
lib/hydra/works/models/characterization/fits_datastream.rb
lib/hydra/works/services/add_file_to_file_set.rb
lib/hydra/works/services/characterization_service.rb
lib/hydra/works/version.rb
spec/hydra/works_spec.rb

Also, rename the `status_message` characterization term to `filestatus_message`, because AF 9.7.1 adds this method to AF::Base objects.

Fix Rubocop violations

---

hydra-works.gemspec

Because hydra-works does not use Rails. Blocked by #262,

Do not declare engine_cart as a dependency, because we do not use engine_cart

---

lib/hydra/works.rb
lib/hydra/works/models/concerns/file_set_behavior.rb
lib/hydra/works/models/concerns/work_behavior.rb
lib/hydra/works/not_collection_validator.rb
spec/hydra/works/models/file_set_spec.rb
spec/hydra/works/models/work_spec.rb

FileSets and Works should barf clearly when a Collection is added as a member

---

lib/hydra/works/models/concerns/work_behavior.rb
spec/hydra/works/models/work_spec.rb

FileSets should not have the assumption that they are ordered.  If you
need FileSets in order, create a set of interstial Work nodes that are
ordered (e.g. Page, Component). Fixes #279

Deprecate ordered_file_sets

---

lib/hydra/works/characterization/schema/document_schema.rb
lib/hydra/works/models/concerns/file_set/characterization/document.rb
solr/config/schema.xml

This PR renames properties `file_author` and `file_language` to `creator` and `language` respectively to prevent a problem downstream when CurationConcerns defines properties that share the same predicate (namely `dc:creator` and `dc:language`) with the to properties in `DocumentSchema`.
~~This PR is here to start a discussion, do not merge yet.~~
~~The `DocumentSchema` class is currently using DublinCore `creator` and `language` predicates. However, these predicates are also used in *CurationConcerns* `BasicMetadata` class. See https://github.com/projecthydra-labs/curation_concerns/blob/master/app/models/concerns/curation_concerns/basic_metadata.rb#L18~~
~~In order to prevent the same RDF predicate being used for two different Ruby properties this PR suggest changing the ones used in …

Rename properties that share predicate with CurationConcerns

---

hydra-works.gemspec

Given that hydra-pcdm is not yet v1.0 (and thus a stable API), I want
to keep the dependency a bit more clamped down. It highlights that
hydra-works and hydra-pcdm are happening in tandem.

Tightening dependency of hydra-pcdm

---

.rubocop.yml
lib/hydra/works/models/characterization/fits_datastream.rb
lib/hydra/works/models/concerns/file_set/virus_check.rb
lib/hydra/works/services/add_file_to_file_set.rb

There were a handful of exclusions for some Rubocop scenarios. This bit
of refactoring is a simple extraction of methods to better comply with
Rubocop.

Refactoring to remove exclusions for rubocop

---

lib/hydra/works.rb
lib/hydra/works/models/concerns/file_set/virus_check.rb
lib/hydra/works/services/virus_checker_service.rb
spec/hydra/works/models/concerns/file_set/virus_check_spec.rb
spec/hydra/works/services/virus_checker_service_spec.rb

One of the major disadvantages of module mixins is that several methods
often get defined on the object. This greatly increases the chance of
method collisions if lots of mixins are used.
So, while preserving much of the outward interface of the
`Hydra::Works::VirusCheck`'s validation, I'm extracting a collaborating
class that can do the heavy lifting against the file.
This involved a bit of additional refactoring as I was encountering
challenges with ClamAV definitions. By relying also on dependency
injection of the system virus scanner, I can more easily test each
piece of the anti-virus process in better isolation.

Extracting VirusCheckService from module mixin

---

lib/hydra/works.rb
lib/hydra/works/services/virus_checker_service.rb
lib/hydra/works/virus_scanner.rb
spec/hydra/works/services/virus_checker_service_spec.rb
spec/hydra/works/virus_scanner_spec.rb
spec/hydra/works_spec.rb

Creates a settable virus scanner class that defaults to ClamAV, if it is present, or sets a null scanner that reports files have no viruses.

Use our own VirusScanner, fixes #296

---

lib/hydra/works/characterization.rb
lib/hydra/works/characterization/schema/base_schema.rb
lib/hydra/works/services/characterization_service.rb
spec/hydra/works/characterization_spec.rb
spec/hydra/works/services/characterization_service_spec.rb

This adjusts HydraWorks to align with recent changes in ActiveFedora regarding mime-type. It also addresses a small bug found with using this with Sufia. In passing a File object for upload, the file will have already been read by an ingest job and therefore needs to be rewound to the beginning in order to be read again for characterization.

Only use mime-type as defined on the file in ActiveFedora

---

.rubocop.yml
.travis.yml
hydra-works.gemspec
lib/hydra/works.rb
lib/hydra/works/characterization.rb
lib/hydra/works/characterization/fits_document.rb
lib/hydra/works/services/characterization_service.rb
spec/hydra/works/models/characterization/fits_document_spec.rb
spec/hydra/works/models/file_set_spec.rb
spec/hydra/works/services/characterization_service_spec.rb

This supports ActiveFedora 11 and removes the dependency on OmDatastream.

Use plain OM::XML::Document without the datastream

---

lib/hydra/works.rb
lib/hydra/works/services/add_file_to_file_set.rb
lib/hydra/works/services/determine_mime_type.rb
lib/hydra/works/services/determine_original_name.rb
spec/hydra/works/services/add_file_to_file_set_spec.rb
spec/hydra/works/services/determine_mime_type_spec.rb
spec/hydra/works/services/determine_original_name_spec.rb

This will ultimately relate to fixing projecthydra/sufia#2553. We interrogate an incoming object about its original name and mime type, providing a values ffor each based on some logic. Testing this was difficult when it was buried in a private method. This surfaces the methods as services which can be more easily tested, as well as exposed to other consuming applications should they wish to make use of them.

Use services for determining mime type and filename

---

lib/hydra/works/services/virus_checker_service.rb
spec/hydra/works/services/virus_checker_service_spec.rb

fixes #313 
If the content has a path just use that
If the file is not saved to fedora use the content
If the file is save use the datastream
This bug was introduced by me in an effort to not read large files into memory.  Unfortunately when the item was not saved the datastream could not be retrieved from fedora.

Changing how the file is retrieved for virus checking

---

lib/hydra/works.rb
lib/hydra/works/services/add_external_file_to_file_set.rb
spec/hydra/works/services/add_external_file_to_file_set_spec.rb

This creates a service class called AddExternalFileToFileSet which acts very
similar to AddFileToFileSet, but instead of expecting binary data, it expects a
URL. This URL will go into the external-content header of the Fedora resource,
and Fedora will automatically redirect to that URL.
The motivation is to provide the basis for more advanced external storage
features higher up in the Hydra stack.

Allows adding URL redirects as files

---

lib/hydra/works/services/add_file_to_file_set.rb

It was missing `file`, the parameter name.

AddFileToFileSet: fix @param documentation

---

hydra-works.gemspec

Fixes issue where `hydra-works-x.y.z.gem` is routinely detected and repaired/quarantined/deleted by Symantec Endpoint Protection and others because of the [EICAR Test String](https://en.wikipedia.org/wiki/EICAR_test_file) that is present in `spec/fixtures`. This PR excludes that fixture from shipping with the gem, but `hydra-works` developers will still need to manually exempt `spec` or `spec/fixtures` from their virus scanner's jurisdiction.

Exclude eicar.txt from .gem to avoid false positives from virus scanners

---

lib/hydra/works/services/determine_original_name.rb

If you aren't calling `#read`, then it isn't part of the method signature.

tweak YARD

---

lib/hydra/works/characterization/fits_document.rb
lib/hydra/works/services/characterization_service.rb
spec/fixtures/fits_netcdf_two_mimetypes.xml
spec/hydra/works/services/characterization_service_spec.rb

This is a little suboptimal because OM exposes all of the terms on the
top level of the instance, so the method is named __cleanup__. The
parsers also do not have a base class to ensure that a given cleanup
method is available, so we use a respond_to? check. The last ugly bit is
that calling `file_mime_type = ...` did not update the value, so the
`send("filetype=", ...)` was the only way I could get this to pass.
There is a new test with FITS output from running against a sample
netCDF file. There may be other types that report multiple mimetypes in
this way, so the cleanup implementation is general (split on comma, pick
the first). It's possible that using an array would be better, but there
are other expectations in the service that enforce a single value.

Fix #334 - Add a cleanup phase to CharacterizationService

---

.rubocop.yml
hydra-works.gemspec
lib/hydra/works/characterization.rb
lib/hydra/works/characterization/fits_document.rb
lib/hydra/works/characterization/schema/audio_schema.rb
lib/hydra/works/characterization/schema/video_schema.rb
spec/fixtures/fits_1.2.0_avi.xml
spec/fixtures/fits_1.2.0_mp3.xml
spec/fixtures/fits_1.2.0_mp4.xml
spec/hydra/works/characterization_spec.rb
spec/hydra/works/models/concerns/file_set/contained_files_spec.rb
spec/hydra/works/services/characterization_service_spec.rb

Fixes #331.
The latest Fits version and many versions before use a different tool (mediainfo) for analysis of audio and video files than was used in prior versions of Fits leading to output with fields in different locations.  This PR adds support for the new locations for data while retaining support for the old locations.
Also included in this PR:
- Add aspect ratio for newer Fits
- Pin activesupport to <5.2 to deal with issues in latest ActiveFedora with Rails 5.2

Fix characterization of audio and video files with Fits 1.2.0

---

Gemfile
hydra-works.gemspec
spec/hydra/works/models/collection_spec.rb

This PR mirrors the one made by @escowles (#303) when reversing the collection->object relationship.  All of the work happens in hydra-pcdm so only tests need to be added here.  This PR points to the branch of hydra-pcdm which has the changes, but it should use a released version when available.

Test reversed nested collection relationships

---

hydra-works.gemspec

This updates the `hydra-file_characterization` to
the newer 1.x versions. 1.0.0 was released in
August of 2018 and 1.1 was released in May 2019.

Update hydra-file_characterization version

---

.circleci/config.yml
Gemfile
hydra-works.gemspec

Supersedes #375 by dropping dependency pins now that dependencies have been released.

Adding Ruby 2.7.z and Rails 6.y.z releases to the CircleCI build configuration

---

.circleci/config.yml
spec/hydra/works/services/persist_derivatives_spec.rb

Resolves #385 and addresses the following:
- Updating the CircleCI Orb to samvera/circleci-orb@1.0
- Using the samvera/ruby_fcrepo_solr_redis_postgres task for ensuring that Solr authentication is supported
- Ensuring that libsqlite3-dev is installed as a system package
- Ensuring that samvera/install_solr_core is used in place of samvera/install_solr_active_fedora_core
- Updating the Ruby releases within the test matrix to 2.7.5, 2.6.9, and 2.5.9

Ensures that CircleCI executes nightly test suites
