- CONTRIBUTING.md
> adds hydra Contribution Guidelines

- README.md
- lib/hydra/works.rb
- lib/hydra/works/services/collection/remove_collection.rb
- lib/hydra/works/services/collection/remove_generic_work.rb
- lib/hydra/works/services/collection/remove_related_object.rb
- lib/hydra/works/services/generic_file/remove_generic_file.rb
- lib/hydra/works/services/generic_file/remove_related_object.rb
- lib/hydra/works/services/generic_work/remove_generic_file.rb
- lib/hydra/works/services/generic_work/remove_generic_work.rb
- lib/hydra/works/services/generic_work/remove_related_object.rb
- spec/hydra/works/services/collection/add_collection_spec.rb
- spec/hydra/works/services/collection/add_generic_work_spec.rb
- spec/hydra/works/services/collection/add_related_object_spec.rb
- spec/hydra/works/services/collection/remove_collection_spec.rb
- spec/hydra/works/services/collection/remove_generic_work_spec.rb
- spec/hydra/works/services/collection/remove_related_object_spec.rb
- spec/hydra/works/services/generic_file/remove_generic_file_spec.rb
- spec/hydra/works/services/generic_file/remove_related_object_spec.rb
- spec/hydra/works/services/generic_work/remove_generic_file_spec.rb
- spec/hydra/works/services/generic_work/remove_generic_work_spec.rb
- spec/hydra/works/services/generic_work/remove_related_object_spec.rb
This is not ready to merge until PR https://github.com/projecthydra-labs/hydra-pcdm/pull/104 is merged into pcdm.
> Add services for removing collections, generic works, generic files, and related objects

- .gitignore
- lib/hydra/works.rb
- lib/hydra/works/services/generic_work/move_generic_file.rb
- spec/hydra/works/services/generic_work/move_generic_file_spec.rb
> Moves a generic file from one generic work to another. 

- spec/hydra/works/services/generic_work/move_generic_file_spec.rb
Reconciles PR #117 and PR #82
Fixes the error that came up in [Travis job #131](https://travis-ci.org/projecthydra-labs/hydra-works/jobs/64632531)
> Reconcile PR #117 and PR #82

- lib/hydra/works/models/concerns/generic_file/versioned_content.rb
- lib/hydra/works/services/generic_file/add_file.rb
- lib/hydra/works/services/generic_file/upload_file.rb
- spec/hydra/works/models/concerns/generic_file/contained_files_spec.rb
- spec/hydra/works/models/concerns/generic_file/versioned_content_spec.rb
- spec/hydra/works/services/generic_file/add_file_spec.rb
- spec/hydra/works/services/generic_file/upload_file_spec.rb
Also cleans up method signature on AddFile.call()  and UploadFile.call()
refs pulibrary/curation_concerns#24
> makes versioning optional in AddFile service.

- Gemfile
- lib/hydra/works.rb
- lib/hydra/works/services/generic_file/persist_derivative.rb
- spec/hydra/works/services/generic_file/persist_derivative_spec.rb
For #130. @flyingzumwalt please review. Do not merge until https://github.com/projecthydra/hydra-derivatives/pull/61 is sorted out.
> Persist dervivatives output service.

- spec/hydra/works/models/generic_work_spec.rb
This is something that was tested in the pcdm branch of sufia.  I'm deleting it from there because it doesn't belong there, but offering it here as test coverage you might want to add.
> test generic_files association on subclass

- lib/hydra/works/services/generic_file/add_file_to_generic_file.rb
- spec/hydra/works/services/generic_file/add_file_to_generic_file_spec.rb
Also refactored to (hopefully) simplify the code.
> Adding a file should not check for viruses twice

- spec/spec_helper.rb
> Adding coveralls/simplecov filter to exclude /spec from test coverage calculation

- spec/hydra/works/models/generic_work_spec.rb
* fixing a few deprecated method names in related tests
* Fixes #87
> Adding test for child_generic_file_ids

- spec/hydra/works/models/collection_spec.rb
- spec/hydra/works/models/generic_work_spec.rb
- spec/hydra/works/services/generic_file/add_related_object_spec.rb
> Removing solr tests

- spec/hydra/works/models/collection_spec.rb
> Unskipping related_objects validation now that hydra-pcdm#153 is resolved

- README.md
- lib/hydra/works/models/concerns/generic_file/virus_check.rb
- lib/hydra/works/models/generic_file.rb
- spec/hydra/works/models/concerns/generic_file/virus_check_spec.rb
> Migrating virus check functionality from CurationConcerns

- spec/hydra/works/models/collection_spec.rb
- spec/hydra/works/models/concerns/block_child_objects_spec.rb
- spec/hydra/works/models/concerns/generic_file/mime_types_spec.rb
- spec/hydra/works/models/generic_file_spec.rb
- spec/hydra/works/models/generic_work_spec.rb
Improves test coverage to above 90% -- fixes #186
> Adding test coverage for poorly-covered classes and modules

- lib/hydra/works/models/concerns/generic_work_behavior.rb
- spec/hydra/works/models/generic_work_spec.rb
Deleted unused method def 'contains=' from spec and lib
> Deleted contains= from spec and lib

- .rubocop.yml
- lib/hydra/works.rb
- lib/hydra/works/errors/full_text_extraction_error.rb
- lib/hydra/works/services/generic_file/full_text_extraction_service.rb
- spec/hydra/works/services/full_text_extraction_service_spec.rb
Move full text extraction from curation concerns to works.
> move full text extraction from curation concerns to works.

- .gitignore
- Rakefile
- config/solrconfig.xml
- lib/tasks/hydra-works_tasks.rake
- lib/tasks/jetty.rake
- spec/hydra/works/services/full_text_extraction_service_spec.rb
Closes #201. Rake tasks pulled down from curation_concerns and full_test_extraction service test runs in travis.
> add hydra_works:jetty:config task

- README.md
> additional jetty config and dependencies

- Gemfile
- README.md
- hydra-works.gemspec
- lib/hydra/works/models/concerns/block_child_objects.rb
- lib/hydra/works/models/concerns/collection_behavior.rb
- lib/hydra/works/models/concerns/generic_file_behavior.rb
- lib/hydra/works/models/concerns/generic_work_behavior.rb
- lib/hydra/works/version.rb
- spec/hydra/works/models/collection_spec.rb
- spec/hydra/works/models/concerns/block_child_objects_spec.rb
- spec/hydra/works/models/concerns/generic_file/virus_check_spec.rb
- spec/hydra/works/models/generic_file_spec.rb
- spec/hydra/works/models/generic_work_spec.rb
Fix for issue https://github.com/projecthydra-labs/hydra-works/issues/211
> Fix 211 - Rework association names. drop parent_ and child_

- lib/hydra/works/services/generic_file/full_text_extraction_service.rb
- spec/hydra/works/services/full_text_extraction_service_spec.rb
Allow passing a local filename to the full-text indexing service. This
allows us to do the ingest without pulling a copy from Fedora. Fixes #217
> full text indexing of a local file

- lib/hydra/works/models/characterization/base_schema.rb
- lib/hydra/works/services/characterization_service.rb
If you do it won't persist. See
https://github.com/ActiveTriples/ActiveTriples/issues/19
> You can't shift onto an ActiveTriples property

- lib/hydra/works/models/concerns/file_set/mime_types.rb
- spec/hydra/works/models/concerns/file_set/mime_types_spec.rb
This was a concern specific to CurationConcerns, so it's been moved
there.  See
https://github.com/projecthydra-labs/curation_concerns/pull/538
> Removed FileSet#file_format

- README.md
Because https://github.com/projecthydra-labs/hydra-works/issues/258
> README should not recommend using `members.<<`

- lib/hydra/works.rb
- lib/hydra/works/models/concerns/collection_behavior.rb
- lib/hydra/works/not_file_set_validator.rb
- lib/hydra/works/services/add_file_to_file_set.rb
- spec/hydra/works/models/collection_spec.rb
- spec/hydra/works/services/persist_derivatives_spec.rb
> Collections should not allow FileSets as members

- hydra-works.gemspec
- lib/hydra/works.rb
> Don't require ActiveFedora::Aggregation anymore

- lib/hydra/works/models/concerns/file_set/virus_check.rb
- spec/hydra/works/models/concerns/file_set/virus_check_spec.rb
- detection method returns true if virus is detected
- custom ActiveModel validation is more idiomatic
> clarify virus detection method names

- lib/hydra/works/services/characterization_service.rb
- spec/fixtures/fits_0.8.5_tiff.xml
- spec/hydra/works/services/characterization_service_spec.rb
- spec/hydra/works/services/persist_derivatives_spec.rb
This can be reviewed; please don't merge until i've run it by the tech list as promised on this week's call.
Update: this is ready for review / merge.
> Only store largest height, width for characterization, fixes #327

- .rubocop.yml
- hydra-works.gemspec
- lib/hydra/works/characterization.rb
- lib/hydra/works/characterization/fits_document.rb
- lib/hydra/works/characterization/schema/audio_schema.rb
- lib/hydra/works/characterization/schema/video_schema.rb
- spec/hydra/works/characterization_spec.rb
- spec/hydra/works/services/characterization_service_spec.rb
Avalon-bundle Issue#2915: Extending Technical Metadata in Generic Work Type
> Av cherrypick

- .travis.yml
- hydra-works.gemspec
> Updating the Travis CI build matrix to test against Ruby releases 2.5.1 and 2.4.4

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE
- README.md
- SUPPORT.md
> Uses the Component Maintenance Working Group doc. templates

- hydra-works.gemspec
- lib/hydra/works/version.rb
Once hydra-pcdm is released this should work under rails 5.2.
> Allow for rails 5.2

- .circleci/config.yml
- Gemfile
> Updates the CircleCI configuration to test against Ruby releases 2.6.3, 2.5.5, and 2.4.6

- .circleci/config.yml
- Gemfile
- hydra-works.gemspec
> Adding Ruby 2.7.z and Rails 6.y.z releases to the CircleCI build configuration

- lib/hydra/works/version.rb
See release notes draft at https://github.com/samvera/hydra-works/releases
> Update version for release

- .circleci/config.yml
- .rubocop.yml
- Gemfile
- hydra-works.gemspec
~Depends on many dependencies with unreleased branches that add support for ruby 3.~
Tests support for ruby 3.2 and rails 7.
> Support latest ruby and rails versions

- hydra-works.gemspec
- lib/hydra/works/version.rb
Included in this release would be:
- #386 
- #389
- #391
- #393
- #394
> Release v2.1.0

- .circleci/config.yml
- hydra-works.gemspec
- solr/conf/_rest_managed.json
- solr/conf/admin-extra.html
- solr/conf/elevate.xml
- solr/conf/mapping-ISOLatin1Accent.txt
- solr/conf/protwords.txt
- solr/conf/schema.xml
- solr/conf/scripts.conf
- solr/conf/solrconfig.xml
- solr/conf/spellings.txt
- solr/conf/stopwords.txt
- solr/conf/stopwords_en.txt
- solr/conf/synonyms.txt
- solr/conf/xslt/example.xsl
- solr/conf/xslt/example_atom.xsl
- solr/conf/xslt/example_rss.xsl
- solr/conf/xslt/luke.xsl
Required re-doing the Solr and Fedora setup because something is wrong with the Solr core creation in the samvera/install_solr_core orb. This also required a local Solr configuration directory to pass into the core creation API; the configuration was taken directly from the one being used in [active_fedora](https://github.com/samvera/active_fedora/tree/main/lib/generators/active_fedora/config/solr/templates/solr/conf).
> Testing for Ruby 3.3 and Rails 7.2
